name: First CI Pipeline

on:
  push:
    branches:
      - master
      - 'feature/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs_on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test



  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: Build Docker image
        run: docker build -t ci-cd-playground .
