name: First CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      

      - name: list directories
        run: pwd

      - name: list files
        run: ls -al

      - name: Print hello
        run: echo "🎉 Hello from GitHub Actions!"
